### ISSUE TITLE
Unlicensed use of cslol-patcher 

### ISSUE THREAD

**Issue by Crauzer** [nylish/ritoskin#6]
Hi, it looks like you are using our (LeagueToolkit) signature on the cslol patcher dll.
![image](https://github.com/user-attachments/assets/dec8da5b-1f4f-4c63-837d-7ad44b59ea6e)

 The [cslol-patcher license](https://github.com/LeagueToolkit/cslol-patcher/blob/master/LICENSE) clearly specifies that any 3rd party redistributing the .dll file in any way needs to remove our signature from the file and sign it with their own one.

> Any party distributing the .dll file included in this software in any way must
re-sign the .dll file with their own key. The original .dll file is signed with
the key of League Toolkit and is distributed under League Toolkit on GitHub.

We would appreciate if you could re-sign the .dll with your own code signing key.

**Comment by Crauzer** [comment]
https://github.com/nylish/ritoskin/commit/70d631df111d58da7d2d62dc8e5df6a7b9392faf#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R45

This is still considered distribution, you're telling your users to just download it straight from us so you don't have to sign it yourself.

**Comment by nylish** [comment]
Hei Filip,

Thank you for your message regarding the `cslol.dll`. I understand your concern about the distribution of your signed DLL. As you noticed, I deleted cslol-dll.dll from the repository as you asked.

Here are the steps I plan to take:
- I will remove the direct download link to `cslol.dll` from my instructions.
- I will clearly state that your project does not distribute the DLL, but I will provide instructions for users to obtain it legally themselves.
- I will not consider re-signing the DLL with my own certificate.
- I appreciate your work and respect your licensing terms. If there's any other way I can comply or if you can provide further guidance, I'm open to it.
